package dev.montb.basickeyboard.ime

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Checks the dictionary that actually ships, rather than the hand-written sample
 * [PinyinEngineTest] uses to pin the ranking rules.
 *
 * The dictionary is generated by `tools/make_pinyin_dict.py` from an external dataset, so it is
 * the one part of the pinyin feature nobody reads before release. A conversion can go wrong
 * quietly and in ways that still parse: the RIME source writes per-reading percentages on exactly
 * the most common characters, and mistaking those for part of the pinyin silently drops 的 and 我
 * while keeping obscure ones, leaving a dictionary that looks large and ranks nonsense. These
 * tests are cheap and would have caught that.
 */
class PinyinDictionaryTest {

    /** Walk up from the working directory so this works whatever Gradle sets it to. */
    private fun projectFile(relative: String): File {
        var dir: File? = File("").absoluteFile
        while (dir != null) {
            val candidate = File(dir, relative)
            if (candidate.isFile) return candidate
            dir = dir.parentFile
        }
        throw AssertionError("could not find $relative from ${File("").absolutePath}")
    }

    private val lines: List<String> by lazy {
        projectFile("src/main/assets/${PinyinEngine.ASSET}").readLines()
    }

    private val dict by lazy { PinyinEngine.parse(lines.asSequence()) }
    private val keys by lazy { dict.keys.sorted() }

    private fun top(input: String, limit: Int = 5): List<String> =
        PinyinEngine.lookup(dict, keys, input, limit).map { it.word }

    @Test
    fun theShippedDictionaryParses() {
        assertTrue("dictionary parsed to nothing", dict.isNotEmpty())
        // A seed of a few hundred would still parse; this guards against shipping one by mistake.
        assertTrue("suspiciously small dictionary: ${dict.size} keys", dict.size > 5_000)
    }

    @Test
    fun everyLineIsWellFormed() {
        val bad = lines.withIndex()
            .filterNot { (_, l) -> l.isBlank() || l.trimStart().startsWith("#") }
            .filterNot { (_, l) ->
                val p = l.trim().split(Regex("\\s+"))
                p.size == 3 && p[0].all { it in 'a'..'z' } && p[2].all { it.isDigit() }
            }
            .map { (i, l) -> "line ${i + 1}: $l" }
        assertTrue("malformed entries:\n" + bad.take(5).joinToString("\n"), bad.isEmpty())
    }

    @Test
    fun theMostCommonCharactersRankFirst() {
        // These are the highest-frequency characters in Chinese. If any of them is not the top
        // candidate for its own pinyin, the frequency data did not survive conversion.
        assertEquals("的", top("de").first())
        assertEquals("我", top("wo").first())
        assertEquals("是", top("shi").first())
        assertEquals("你", top("ni").first())
        assertEquals("好", top("hao").first())
    }

    @Test
    fun commonPhrasesResolve() {
        // Multi-syllable entries are what make the keyboard usable rather than a character picker.
        assertEquals("你好", top("nihao").first())
        assertEquals("我的", top("wode").first())
        assertEquals("中国", top("zhongguo").first())
        assertEquals("我们", top("women").first())
        assertEquals("谢谢", top("xiexie").first())
    }

    @Test
    fun simplifiedFormsOutrankTraditionalOnes() {
        // The suite targets a mainland device, so where a character has both forms the simplified
        // one must come first. Asserting a specific winner per key would be wrong (guo is 过, not
        // 国, because the aspect marker is commoner than "country"); what matters is the ordering
        // between the two forms of the SAME character.
        for ((key, forms) in listOf(
            "guo" to ("国" to "國"),
            "shi" to ("时" to "時"),
            "men" to ("们" to "們"),
            "hui" to ("会" to "會")
        )) {
            val (simplified, traditional) = forms
            val ranked = top(key, 60)
            val s = ranked.indexOf(simplified)
            val t = ranked.indexOf(traditional)
            assertTrue("$key: simplified $simplified missing from the candidates", s >= 0)
            assertTrue(
                "$key: traditional $traditional outranks simplified $simplified",
                t < 0 || s < t
            )
        }
    }

    @Test
    fun prefixesPredictLongerWords() {
        // Typing a partial phrase should still surface it, which is the prefix path in lookup().
        assertTrue("你好 not predicted from 'niha'", top("niha", 20).contains("你好"))
    }

    @Test
    fun aKeyCanOfferSeveralCandidates() {
        // A single top hit for a common syllable would mean the alternatives were lost.
        assertTrue("too few candidates for 'shi'", top("shi", 10).size >= 5)
    }
}
