#!/usr/bin/env python3
"""
Convert an open pinyin dataset into BasicKeyboard's assets/pinyin_dict.txt format:

    <pinyin> <word> <frequency>

where <pinyin> is the concatenated TONELESS syllables (nihao) and u-with-diaeresis is
written "v" (lv = 绿), the convention every Chinese IME accepts.

Input formats, auto-detected per line:

  1. RIME dict (luna_pinyin.dict.yaml and friends)   你好<TAB>ni hao<TAB>1000
     word first, space-separated pinyin, optional trailing weight. The YAML header
     before the line containing only "..." is skipped automatically.
  2. phrase-pinyin-data / pinyin-data (mozillazg)    你好: nǐ hǎo
  3. Already-converted passthrough                   nihao 你好 1000

Usage:

    python3 tools/make_pinyin_dict.py INPUT [INPUT ...] > app/src/main/assets/pinyin_dict.txt

Duplicates are merged keeping the highest frequency. Output is sorted by pinyin, then by
descending frequency, which is also the order the app ranks candidates in.

LICENSING: the suite is GPL v3, so only import GPLv3-compatible data. Known-good sources:
RIME dictionaries (GPL-3), mozillazg's pinyin-data / phrase-pinyin-data (MIT),
CC-CEDICT (CC BY-SA 4.0, which Creative Commons declares one-way compatible with GPLv3).
Record whichever you used in the repo so the attribution is not lost.
"""

import re
import sys
import unicodedata

HANZI = re.compile(r"[㐀-䶿一-鿿]")
PINYIN_KEY = re.compile(r"[a-z]+")


def toneless(text: str) -> str:
    """Strip tone marks; map u-with-diaeresis to 'v'.  'nǐ hǎo' -> 'ni hao', 'lǜ' -> 'lv'.

    Decomposes first so precomposed toned vowels (ǖ ǘ ǚ ǜ) are handled, then folds each base
    character together with its combining marks: a 'u' carrying a diaeresis becomes 'v', every
    other mark is simply dropped.
    """
    d = unicodedata.normalize("NFD", text)
    out = []
    i, n = 0, len(d)
    while i < n:
        base = d[i]
        i += 1
        marks = []
        while i < n and unicodedata.combining(d[i]):
            marks.append(d[i])
            i += 1
        if base in "uU" and "̈" in marks:
            out.append("v")
        else:
            out.append(base)
    return "".join(out).lower()


def parse_line(line: str):
    """Return (pinyin_key, word, freq) or None if the line carries no entry."""
    s = line.strip()
    if not s or s.startswith("#") or s.startswith("---") or s == "...":
        return None

    # Format 2:  你好: nǐ hǎo
    if ":" in s and HANZI.search(s.split(":", 1)[0]):
        word, py = s.split(":", 1)
        return _entry(toneless(py).replace(" ", ""), word.strip(), 1)

    parts = re.split(r"\s+", s)
    if len(parts) < 2:
        return None

    # Format 3: already converted, pinyin first.
    if not HANZI.search(parts[0]):
        freq = int(parts[2]) if len(parts) > 2 and parts[2].isdigit() else 1
        return _entry(toneless(parts[0]), parts[1], freq)

    # Format 1 (RIME): word first, then the syllables, then an optional weight.
    word, rest = parts[0], parts[1:]
    freq = 1
    if rest and re.fullmatch(r"\d+(\.\d+)?", rest[-1]):
        freq = max(1, int(float(rest[-1])))
        rest = rest[:-1]
    if not rest:
        return None
    return _entry(toneless("".join(rest)), word, freq)


def _entry(key: str, word: str, freq: int):
    if not key or not PINYIN_KEY.fullmatch(key):
        return None
    if not word or not HANZI.search(word):
        return None
    return key, word, freq


def main(paths):
    if not paths:
        print(__doc__, file=sys.stderr)
        return 1
    best = {}
    for path in paths:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                parsed = parse_line(line)
                if not parsed:
                    continue
                key, word, freq = parsed
                slot = (key, word)
                if freq > best.get(slot, -1):
                    best[slot] = freq

    print("# Generated by tools/make_pinyin_dict.py -- do not hand-edit.")
    print("# Format: <pinyin> <word> <frequency>. Pinyin is concatenated toneless syllables,")
    print("# u-with-diaeresis written as 'v'. Higher frequency ranks first.")
    print(f"# {len(best)} entries.")
    for (key, word), freq in sorted(best.items(), key=lambda kv: (kv[0][0], -kv[1], kv[0][1])):
        print(f"{key} {word} {freq}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
